### ISSUE TITLE
Unspecified client-side jade dependency

### ISSUE THREAD

**Issue by raineorshine** [two-n/grunt-jade-client#1]
There's a dependency on jade.js and realtime.js for the call to jade.escape. This was undocumented and gave me some troubles when installing.

**Comment by raineorshine** [comment]
http://stackoverflow.com/questions/13814153/jade-escape-is-undefined-on-compiled-jade-template

**Comment by ragingsquirrel3** [comment]
In your opinion, would a change to the docs be the best way to address this?  Another option would be to build the template file with the dependency included, although I would argue that should not be default behavior.

**Comment by raineorshine** [comment]
I think building it into the template file is how http://projects.jga.me/clientjade does it but I'm not sure. Updating the docs is a good short-term solution. If I had the time, I'd want to compare this with clientjade to see if there is a real difference, or if it might be worth integrating the two, i.e. building
a grunt wrapper for clientjade.

**Comment by ragingsquirrel3** [comment]
Thanks for the input, and I've added a small section to the readme with instructions on how to use in the client, with a note about runtime.js, and a copy of that file in the repo.

On the issue of clientjade vs this repo, I think the difference is just syntax, and that clientjade includes the dependencies in the output.  Jade compiles templates for the client, and these two repos are just two different ways of exposing that functionality.

Adding runtime.js into the build would be a nice option, but not default behavior, in my opinion.  People using RequireJs (or something similar) tend to avoid builds that have the dependency because that's what RequireJs is meant for, managing dependencies.

**Comment by raineorshine** [comment]
That sounds like a good assessment. Make that clear in the README and then
people can make the right decision for them. Thanks!

**Comment by ragingsquirrel3** [comment]
Cool, done, and someday I may add this as an option.
